### ISSUE TITLE
Fedora 32 MATE 安装了 openSUSE Tumbleweed 的 luna-calendar，日历中的汉字显示成了拼音

### ISSUE THREAD

**Issue by moontide** [yetist/lunar-calendar#3]
在 openSUSE Tumbleweed 中的日历中看到了农历，查了查，才知道 lunar-calendar 这个软件。

由于 Fedora 仓库中没有 lunar-calendar，所以就从 openSUSE Tumbleweed 的仓库中下载了相关的 rpm 安装包，并安装，安装没有报错，重启后的确能看到农历了，但类似“十三”这样的文字就变成了“shisan”，但类似“建军节”却又显示的是正常汉字。

![2020-08-18 10-51-05屏幕截图](https://user-images.githubusercontent.com/1464560/90465262-952b7b00-e141-11ea-8516-819ddf518803.png)

**Comment by hillwoodroc** [comment]
你还需要安装 lunar-calendar-lang 这个包，openSUSE 的分包方式和 Fedora 是不一样的。

**Comment by moontide** [comment]
> 你还需要安装 lunar-calendar-lang 这个包，openSUSE 的分包方式和 Fedora 是不一样的。
在 Tumbleweed 仓库里没找到名称为 `lunar-calendar-lang` 的包

**Comment by moontide** [comment]
> 你还需要安装 lunar-calendar-lang 这个包，openSUSE 的分包方式和 Fedora 是不一样的。

在 Tumbleweed 仓库里没找到名称为 lunar-calendar-lang 的包

**Comment by yetist** [comment]
是不是没有安装mo文件？

看看这个输出： `find /usr/share/locale/ -name lunar-calendar.mo`

**Comment by moontide** [comment]
> 是不是没有安装mo文件？
> 
> 看看这个输出： `find /usr/share/locale/ -name lunar-calendar.mo`

# 在 Fedora 中查找，的确没有

	# find /usr -iname "*lunar-calendar*"
	/usr/share/licenses/lunar-calendar
	/usr/share/doc/packages/lunar-calendar
	/usr/lib64/liblunar-calendar-3.0.so.1.0.0
	/usr/lib64/liblunar-calendar-3.0.so.1
	/usr/lib64/gtk-3.0/modules/liblunar-calendar-module.so


# 在 openSUSE 中查找，有，看来，的确是有个 lunar-calendar-lang 包，虽然我肉眼没找到…

	tx300:/ # find /usr/share/locale/ -name lunar-calendar.mo
	/usr/share/locale/zh_CN/LC_MESSAGES/lunar-calendar.mo
	/usr/share/locale/zh_HK/LC_MESSAGES/lunar-calendar.mo
	/usr/share/locale/zh_TW/LC_MESSAGES/lunar-calendar.mo


	tx300:/ # zypper wp /usr/share/locale/zh_CN/LC_MESSAGES/lunar-calendar.mo
	命令 'what-provides' 已被 'search --provides --match-exact' 替换。
	全部可用选项请参考 'help search'。
	正在加载软件源数据...
	正在读取已安装的软件包...

	S | Name                | Summary                                 | Type
	--+---------------------+-----------------------------------------+-------
	i | lunar-calendar-lang | Translations for package lunar-calendar | 软件包

**Comment by moontide** [comment]
好吧，我找错架构了，`lunar-calendar-lang` 包在 noarch 架构里，我一直在 x86_64 里找…

# lunar-calendar-lang、 lunar-calendar-doc、 lunar-date-lang、lunar-date-doc 包在 noarch 架构文件夹里
http://mirrors.ustc.edu.cn/opensuse/tumbleweed/repo/oss/noarch/

# 其他的文件在各自的架构文件夹里
http://mirrors.ustc.edu.cn/opensuse/tumbleweed/repo/oss/x86_64/
http://mirrors.ustc.edu.cn/opensuse/tumbleweed/repo/oss/i586/

# 安装了 `lunar-calendar-lang` 和 `lunar-date-lang` 包后，重启，日历中的汉字显示正常了

![2020-12-29 10-26-03 创建的截图](https://user-images.githubusercontent.com/1464560/103254701-5d6ef280-49c1-11eb-8c54-73b6de542941.png)

----

谢谢  @hillwoodroc @yetist
